### ISSUE TITLE
TRACE_TASK() not working..

### ISSUE THREAD

**Issue by songzeceng** [LITMUS-RT/litmus-rt#20]
I tried to show some debug information with the guidance of http://www.litmus-rt.org/create_plugin/plugin_step_3.html and write the following code in my litmus/sched_demo.c
```
#include <litmus/debug_trace.h>

.............

static long demo_admit_task(struct task_struct* task) {
    TRACE_TASK(task, "The task was rejected by demo plugin!\n");
    return -EINVAL;
}
```
and turn on the TRACE() debugging under LITMUS^RT->Tracing. I can compile my sched_demo into the kernel of litmus but I cannot get the debug output
```
root@ubuntu:/home/szc# setsched demo
root@ubuntu:/home/szc# tail -f /dev/litmus/log > debug.txt &
[1] 9082
root@ubuntu:/home/szc# rtspin 10 100 0.1
could not become RT task: Invalid argument
root@ubuntu:/home/szc# cat debug.txt
root@ubuntu:/home/szc#
```

**Comment by GElliott** [comment]
@songzeceng You may need to first select which Litmus scheduler plugin you want to use (e.g., G-EDF).  I suppose `setsched` should have done that, but maybe it's case-sensitive?  I believe that there should be a file in `/proc/litmus` that indicates which scheduler plugin is currently running.

**Comment by songzeceng** [comment]
You mean I should set scheduler to G-EDF first and then set scheduler to my own demo?That is ... absurd somehow..
What I am trying is boot with litmusRT、set scheduler to my demo using ```setsched demo```、checkout the current scheduler with ```showsched```、schedule job with my demo and show the debug information. All the shells used after booting litmus are as following
```
root@ubuntu:/home/szc# setsched demo
root@ubuntu:/home/szc# showsched
demo
root@ubuntu:/home/szc# tail -f /dev/litmus/log > debug.txt &
[1] 9082
root@ubuntu:/home/szc# rtspin 10 100 0.1
could not become RT task: Invalid argument
root@ubuntu:/home/szc# cat debug.txt
root@ubuntu:/home/szc#
```
And my problem is there is not debug information in debug.txt as showing in the official guidance

**Comment by brandenburg** [comment]
Have you verified that debug tracing is enabled in the kernel configuration?

**Comment by songzeceng** [comment]
Verified at the beginning
![Uploading IMG_20201013_171904.jpg…]()

**Comment by JoshuaJB** [comment]
The TRACE log may not have been flushed to the file yet. Try killing tail before you read the output file.

**Comment by songzeceng** [comment]
> The TRACE log may not have been flushed to the file yet. Try killing tail before you read the output file.

Thanks for your advice but still not working. Here are my commands below
```
root@rtlab-computer:/home/rtlab/szc# setsched demo
root@rtlab-computer:/home/rtlab/szc# tail -f /dev/litmus/log > debug.txt &
[1] 9170
root@rtlab-computer:/home/rtlab/szc# ps -ef | grep tail
root      9170  2669  0 22:17 pts/0    00:00:00 tail -f /dev/litmus/log
root      9172  2669  0 22:17 pts/0    00:00:00 grep --color=auto tail
root@rtlab-computer:/home/rtlab/szc# rtspin 10 100 0.1
could not become RT task: Invalid argument
root@rtlab-computer:/home/rtlab/szc# kill -9 9170
root@rtlab-computer:/home/rtlab/szc# ps -ef | grep tail
root      9175  2669  0 22:18 pts/0    00:00:00 grep --color=auto tail
[1]+  Killed                  tail -f /dev/litmus/log > debug.txt
root@rtlab-computer:/home/rtlab/szc# cat debug.txt 
root@rtlab-computer:/home/rtlab/szc# 
```
And my source file is as simple as below:
```
#include <linux/module.h>
#include <litmus/preempt.h>
#include <litmus/sched_plugin.h>
#include <litmus/debug_trace.h>


static struct task_struct* demo_schedule(struct task_struct* prev) {
    sched_state_task_picked();
    return NULL;
}


static long demo_admit_task(struct task_struct* task) {
    TRACE_TASK(task, "The task was rejected by demo plugin!\n");
    return -EINVAL;
}


static struct sched_plugin demo_plugin = {
    .plugin_name = "demo",
    .schedule    = demo_schedule,
    .admit_task  = demo_admit_task,
};


static int __init init_demo(void) {
    return register_sched_plugin(&demo_plugin);
}
```

**Comment by wutianze** [comment]
Same issue, my debug.txt is empty too.

**Comment by wutianze** [comment]
I solved the issue by replacing `tail -f` with `cat`.

**Comment by songzeceng** [comment]
> I solved the issue by replacing `tail -f` with `cat`.
So did I！Thanks a lot！The new command "cat /dev/litmus/log > debug.txt &" does work for me
