### ISSUE TITLE
Cannot boot because of error "The initrd is too large"

### ISSUE THREAD

**Issue by songzeceng** [LITMUS-RT/litmus-rt#21]
I build and install the litmusRT in another computer with Ubuntu18.04 x86_64 followed the guidance of http://www.litmus-rt.org/installation.html.

After installation and reboot I can see the litmus option in the boot menu, but when I try to boot with it, I get error "Error: the initrd is too large" and "Kernel panic - not syncing: VFS: Unable to mount foot fs on unknown-block(0,0)" after typing enter.

Besides, there is an error when I install litmus but it does not have an impact on producing boot menu entry
```
root@rtlab-computer:/home/rtlab/szc/litmus/litmus-rt# make install
......
 * dkms: running auto installation service for kernel 4.9.30-litmus                                                                                  
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...(bad exit status: 2)
unset ARCH; env NV_VERBOSE=1 'make' -j8 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=4.9.30-litmus IGNORE_XEN_PRESENCE=1 IGNORE_CC_MISMATCH=1 SYSSRC=/lib/modules/4.9.30-litmus/build LD=/usr/bin/ld.bfd modules...(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-4.9.30-litmus is not supported
Error! Bad return status for module build on kernel: 4.9.30-litmus (x86_64)
Consult /var/lib/dkms/nvidia/415.27/build/make.log for more information.
                                                                                                                                              [ OK ]
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.9.30-litmus /boot/vmlinuz-4.9.30-litmus
update-initramfs: Generating /boot/initrd.img-4.9.30-litmus
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.9.30-litmus /boot/vmlinuz-4.9.30-litmus
run-parts: executing /etc/kernel/postinst.d/update-notifier 4.9.30-litmus /boot/vmlinuz-4.9.30-litmus
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 4.9.30-litmus /boot/vmlinuz-4.9.30-litmus
Sourcing file `/etc/default/grub'
Generating grub configuration file ...
.....
Adding boot menu entry for EFI firmware configuration
done
```
And the content of the log file mentioned above  is showing below
```
root@rtlab-computer:/home/rtlab/szc/litmus/litmus-rt# cat /var/lib/dkms/nvidia/415.27/build/make.log
DKMS make.log for nvidia-415.27 for kernel 4.9.30-litmus (x86_64)
2020年 10月 20日 星期二 21:07:31 CST
Makefile:19: /Kbuild: No such file or directory
make[2]: *** No rule to make target '/Kbuild'.  Stop.
```
But I cannot find any make information related to /Kbuild with the correct line number(19) in the source tree of litmus
```
root@rtlab-computer:/home/rtlab/szc/litmus/litmus-rt# find . -name "Makefile" | xargs grep "/Kbuild"
./Makefile:scripts/Kbuild.include: ;
./Makefile:include scripts/Kbuild.include
./Makefile:	$(if $(wildcard $(srctree)/arch/$(hdr-arch)/include/uapi/asm/Kbuild),, \
./arch/s390/Makefile:# See arch/s390/Kbuild for content of core part of the kernel
./arch/x86/Makefile:# See arch/x86/Kbuild for content of core part of the kernel
./arch/mips/Makefile:include arch/mips/Kbuild.platforms
./arch/mips/Makefile:# See arch/mips/Kbuild for content of core part of the kernel
./arch/mips/boot/compressed/Makefile:include $(srctree)/arch/mips/Kbuild.platforms
./arch/arc/Makefile:# See arch/arc/Kbuild for content of core part of the kernel
./arch/tile/Makefile:# See arch/tile/Kbuild for content of core part of the kernel
./arch/sparc/Makefile:# See arch/sparc/Kbuild for the core part of the kernel
root@rtlab-computer:/home/rtlab/szc/litmus/litmus-rt# 
```
I have no idea whether it is the cause of the error "The initrd is too large".I also tried to run the command
```
find . -name *.ko -exec strip --strip-unneeded {} +
``` 
to decrease the size of initrd.img-4.9.30-litmus and vmlinuz-4.9.30-litmus. Success in decreasing the size (7MB current, same with origin Linux kernel) but not in boot with litmus (same error)
Some blogs say this error can be fixed by disabling memory hole in the bios. But there is no such menu in my bios at all....

**Comment by brandenburg** [comment]
As LITMUS^RT doesn't have any kernel modules, the initrd size problem is unlikely to be related to LITMUS^RT. Try building and install a custom Linux kernel *without* the LITMUS^RT patch first, and once you get that to boot properly, you should be in a good position to work with LITMUS^RT, too. 

Trying to debug general boot problems with the LITMUS^RT patch already applied is generally not recommended.

**Comment by songzeceng** [comment]
I build Linux kernel 5.4 and boot successfully(Nvidia driver down).Then I retried the whole litmus build and install process, resulting in the same error during reboot with litmus-4.9.30

**Comment by brandenburg** [comment]
You should build the same base kernel first, i.e., Linux 4.9.30, to make sure that works by itself.

**Comment by songzeceng** [comment]
Jesus, success after installation in linux-4.9.30 as you said! Thanks!
